from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep

opt = webdriver.ChromeOptions()
opt.add_experimental_option('detach', True)
opt.add_argument('--disable-notifications')

dr = webdriver.Chrome(options=opt)
dr.maximize_window()

dr.get('https://demoapps.qspiders.com/ui/frames?sublist=0')
sleep(1)
dr.switch_to.frame(0)
sleep(1)
dr.find_element(By.ID, 'username').send_keys('Hello')
dr.find_element(By.ID, 'password').send_keys('Teddy Bear')
dr.find_element(By.ID, 'submitButton').click()
dr.switch_to.default_content()
sleep(1)
dr.find_element(By.XPATH, '//a[text()="Nested iframe"]').click()
sleep(1)
dr.switch_to.frame(0)
sleep(1)
dr.switch_to.frame(0)
sleep(1)
dr.find_element(By.ID, 'email').send_keys('Admin@gmail.com')
dr.find_element(By.ID, 'password').send_keys('Admin@1234')
dr.find_element(By.ID, "confirm-password").send_keys('Admin@1234')
dr.find_element(By.ID, 'submitButton').click()
dr.switch_to.default_content()
sleep(1)
dr.find_element(By.XPATH, '//a[text()="Multiple iframe"]').click()
sleep(1)
dr.switch_to.frame(0)
sleep(1)
dr.find_element(By.ID, 'email').send_keys("Admin@gmail.com")
dr.find_element(By.ID, 'password').send_keys('Admin@1234')
dr.find_element(By.ID, 'confirm-password').send_keys('Admin@1234')
dr.find_element(By.ID, 'submitButton').click()
sleep(1)
dr.switch_to.parent_frame()
sleep(1)
dr.switch_to.frame(1)
sleep(1)
dr.find_element(By.ID, 'username').send_keys('SuperAdmin@gmail.com')
dr.find_element(By.ID, 'password').send_keys('SuperAdmin@1234')
dr.find_element(By.ID, 'submitButton').click()
dr.switch_to.default_content()
sleep(1)
dr.find_element(By.XPATH, '//a[text()="Nested with Multiple iframe"]').click()
sleep(1)
dr.switch_to.frame(0)
sleep(1)
a = dr.find_element(By.XPATH, '//div[@class="form_container"]/iframe')
dr.switch_to.frame(a)
sleep(1)
email = dr.find_element(By.XPATH, '//div[@class="form-group"]/iframe')
dr.switch_to.frame(email)
sleep(1)
dr.find_element(By.ID, 'email').send_keys('Admin@gmail.com')
dr.switch_to.parent_frame()
sleep(1)
pas = dr.find_element(By.XPATH, '(//div[@class="form-group"]/iframe)[2]')
dr.switch_to.frame(pas)
dr.find_element(By.ID, 'password').send_keys('Admin@1234')
dr.switch_to.parent_frame()
sleep(1)
confirm_pas = dr.find_element(By.XPATH, '(//div[@class="form-group"]/iframe)[3]')
dr.switch_to.frame(confirm_pas)
dr.find_element(By.ID, 'confirm').send_keys('Admin@1234')
dr.switch_to.parent_frame()
sleep(1)
dr.switch_to.frame(3)
dr.find_element(By.ID, 'submitButton').click()
